name: 'Build Isabelle session'
author: 'Wolfgang Jeltsch'
description:
  GitHub action that builds an Isabelle session in quick-and-dirty mode
  with PDF document generation and uploads the generated PDF document as
  a GitHub Actions artifact; intended to be run on `ubuntu-latest` in
  the `texlive/texlive:latest` container
inputs:
  session-name:
    description:
      Name of the session
    required: true
  chapter-name:
    description:
      Name of the chapter the session belongs to
    required: true
  source-path:
    description:
      Path to the source directory of the session relative to
      `$GITHUB_WORKSPACE`
    required: false
    default: '.'
  isabelle-version:
    description:
      Isabelle version to use for building
    required: true
  afp-sessions:
    description:
      Space-separated list of needed Isabelle sessions from the Archive
      of Formal Proofs, each specified as `⟨session-name⟩:⟨version⟩`
      with `⟨version⟩` being either `⟨year⟩-⟨month⟩-⟨day⟩` or `current`
    required: false
    default: ''
  github-sessions:
    description:
      Space-separated list of needed Isabelle sessions from other GitHub
      repositories, each specified as `⟨user-name⟩/⟨repository⟩:⟨path⟩`
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: 'Get Isabelle from cache if available'
      uses: actions/cache@v3
      with:
        key: isabelle-${{ inputs.isabelle-version }}-linux
        path: /opt/Isabelle${{ inputs.isabelle-version }}
    - name: 'Get Isabelle from upstream if not found in cache'
      shell: sh
      run: |
        if [ ! -e '/opt/Isabelle${{ inputs.isabelle-version }}' ]
        then
          curl --fail --silent --show-error \
            'https://isabelle.in.tum.de/website-Isabelle${{ inputs.isabelle-version }}/dist/Isabelle${{ inputs.isabelle-version }}_linux.tar.gz' |
          tar --directory=/opt --extract --gzip
        fi
    - name: 'Create configuration directory'
      shell: sh
      run: |
        mkdir -p "$HOME/.isabelle/Isabelle${{ inputs.isabelle-version }}"
    - name: 'Install required Isabelle sessions from the AFP'
      shell: sh
      run: |
        mkdir /opt/afp-sessions
        for session in ${{ inputs.afp-sessions }}
        do
          name=$(echo "$session" | cut -d : -f 1)
          version=$(echo "$session" | cut -d : -f 2)
          curl --fail --silent --show-error \
            "https://www.isa-afp.org/release/afp-$name-$version.tar.gz" |
          tar --directory=/opt/afp-sessions --extract --gzip
          echo \
            "/opt/afp-sessions/$name" \
            >> "$HOME/.isabelle/Isabelle${{ inputs.isabelle-version }}/ROOTS"
        done
    - name: 'Install required Isabelle sessions from GitHub'
      shell: sh
      run: |
        for session in ${{ inputs.github-sessions }}
        do
          repo=$(echo "$session" | cut -d : -f 1)
          path=$(echo "$session" | cut -d : -f 2)
          account=$(echo "$repo" | cut -d / -f 1)
          mkdir -p "/opt/github-repos/$account"
          curl --fail --silent --show-error \
            "https://codeload.github.com/$repo/zip/refs/heads/master" \
            > "/opt/github-repos/$repo.zip"
          unzip -d "/opt/github-repos/$account" \
            "/opt/github-repos/$repo.zip"
          echo \
            "/opt/github-repos/$repo-master/$path" \
            >> "$HOME/.isabelle/Isabelle${{ inputs.isabelle-version }}/ROOTS"
        done
    - name: 'Build'
      shell: sh
      run: |
        '/opt/Isabelle${{ inputs.isabelle-version }}/bin/isabelle' \
          build \
          -o quick_and_dirty \
          -o document=pdf \
          -P output \
          -D '${{ inputs.source-path }}'
    - name: 'Upload document'
      uses: actions/upload-artifact@v3
      with:
        name: document
        path: output/${{ inputs.chapter-name }}/${{ inputs.session-name }}/document.pdf
